### ISSUE TITLE
CREATE HTML PAGE

### ISSUE THREAD

**Issue by PhilipMcF** [PhilipMcF/Project-1#10]
**Description:** The 'Notetaker' application needs an MVP built in HTML and it's structure based on the attached wireframe: 'Wireframe Version 1.0'.

**User Story:**

As an notetaker application end-user,
I need a webpage organized logically,
so I can create, search, delete and display note text in a centralized location.

**Acceptance Criteria:**

The HTML page has the following structures:

1. A main header section displaying the subject name.
2. An aside column on the left side of the page.
3. A main content area to display note content.
4. Button to active a modal form window.
5. CDN link to Materialize framework.

 

[wireframe_project_one.pdf](https://github.com/user-attachments/files/16367396/wireframe_project_one.pdf)

**Comment by ghost** [comment]
Acceptance criteria complete. Will review with team on 7/24/24 class.
