### ISSUE TITLE
ADD RESPONSIVENESS FOR DIFFERENT DISPLAYS/DEVICES

### ISSUE THREAD

**Issue by PhilipMcF** [PhilipMcF/Project-1#11]
Description: Prepare the application for different devices and screen sizes.

Acceptance Criteria:

- Implement three screen sizes minimum. (Two different breakpoints) Phone, tablet and desktop.
- Different font sizes per device and screen size.
- Implement a collapsable menu. *Specifically on mobile.
- Choose color scheme. Build off existing colors from Materialize: https://materializecss.com/color.html
- *If images added, make the images responsive.

**Comment by ghost** [comment]
**Olyad Kitila Completed This Story.**
