### ISSUE TITLE
MODAL

### ISSUE THREAD

**Issue by PhilipMcF** [PhilipMcF/Project-1#9]
**Description:** For an enhanced application user experience, a modal window will be initialized when the 'add' button in clicked from the HTML page.

**User Story:**

As an end-user for the application,
I want a modal window to appear when I click on an element,
so that I don't need to be redirected to another page to complete user actions.

**Acceptance Criteria:**

The requirements of the modal include:

1. A content box large enough to contain a form.
2. The background will be transparent black allowing the underneath webpage still be visible.
3. Javascript will be added to show the modal on click.
4. Connect and test the connection between the 'add' button, javascript and modal HTML.

**Comment by ghost** [comment]
Per Phillip,

Original: ask if you want to delete note?
MAYBE: same page modal note editor.
